name: Build AnVIL Image
on: push
jobs:
  test:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set branch name
        id: branch
        run: echo "::set-output name=name::$(BRANCH_NAME=${GITHUB_REF##*/}; echo ${BRANCH_NAME/release_/}-auto)"

      - name: Login to Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to quay.io
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY_URL: quay.io

      - run: docker build . -t galaxy/galaxy-anvil:${{ steps.branch.outputs.name }} -f .k8s_ci.Dockerfile

      - name: Push to Docker Hub with branch name
        uses: actions-hub/docker@master
        with:
          args: push galaxy/galaxy-anvil:${{ steps.branch.outputs.name }}

      - run: docker tag galaxy/galaxy-anvil:${{ steps.branch.outputs.name }} quay.io/galaxyproject/galaxy-anvil:${{ steps.branch.outputs.name }}

      - name: Push to quay.io with branch name
        uses: actions-hub/docker@master
        with:
          args: push quay.io/galaxyproject/galaxy-anvil:${{ steps.branch.outputs.name }}
